# Generated by Django 4.2.dev20220823112418 on 2022-08-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="OtherArticle",
        ),
    ]
