name: Build & Upload

on:
  # Trigger on pushes to the main branch only.
  push:
    branches: [ main ]

  # Or run manually.
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: btnapp/btn-django-sphinx-deploy-action@v1
