name: Build & Upload

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Or run manually.
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
      - name: Build docs
        run: make json
      - name: Install SSH key
        uses: carltongibson/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        # Initial test command to check config.
      - name: command over ssh
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ~/.ssh/id_rsa 'pwd;date'
